model_VTE <- readRDS("VTE Risk Assessment Model for Lymphoma.rds")
model_PEDVT <- readRDS("PE/LE-DVT Risk Assessment Model for Lymphoma.rds")
# summary(model_VTE)
your_data <- read.csv("sample_data.csv")
your_data$predited_VTE_incidence<- predict(model_VTE, newdata =your_data, type="risk",times = 6)
your_data$predited_PEDVT_incidence<- predict(model_PEDVT, newdata =your_data, type="risk",times = 6)
